# Generated by Django 4.1.4 on 2022-12-27 06:46

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sessions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('College_Name', models.CharField(blank=True, max_length=500, null=True)),
                ('College_Address', models.CharField(blank=True, max_length=100, null=True)),
                ('State', models.CharField(blank=True, max_length=100, null=True)),
                ('City', models.CharField(blank=True, max_length=100, null=True)),
                ('Pincode', models.CharField(blank=True, max_length=100, null=True)),
                ('Phone_Number', models.CharField(blank=True, max_length=100, null=True)),
                ('Updated_On', models.DateField(blank=True, null=True)),
                ('Remarks', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ('State',),
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Name_Of_Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Application_Assertion_Form', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/')),
                ('Ethic_Communitee_Approval', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/')),
                ('Informed_Concent_Form', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/')),
                ('Case_Study_Form', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/')),
                ('Student_Questionnare', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/')),
                ('Objective', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/')),
                ('Project_Title', models.CharField(max_length=200, null=True, validators=[django.core.validators.MaxLengthValidator(200)], verbose_name='Title')),
                ('Project_introduction', models.CharField(blank=True, max_length=2100, null=True, validators=[django.core.validators.MaxLengthValidator(2100)], verbose_name='Introduction')),
                ('Project_objective', models.CharField(blank=True, max_length=700, null=True, validators=[django.core.validators.MaxLengthValidator(700)], verbose_name='Objectives')),
                ('Project_methodology', models.CharField(blank=True, max_length=5600, null=True, validators=[django.core.validators.MaxLengthValidator(5600)], verbose_name='Methodology')),
                ('Project_implication', models.CharField(blank=True, max_length=700, null=True, validators=[django.core.validators.MaxLengthValidator(700)], verbose_name='Implications')),
                ('Project_reference', models.CharField(blank=True, max_length=2100, null=True, validators=[django.core.validators.MaxLengthValidator(2100)], verbose_name='References')),
                ('Type_Of_Study', models.CharField(choices=[('Literary Research', 'Literary Research'), ('Clinical Research', 'Clinical Research'), ('Drug Research -  Medicinal Plant Research, Drug Standardization, Pharmacological Research', 'Drug Research -  Medicinal Plant Research, Drug Standardization, Pharmacological Research')], max_length=100, null=True)),
                ('Total_Marks', models.IntegerField(blank=True, default=0, null=True)),
                ('final_submit', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=100, null=True)),
                ('Date_Created', models.DateField(auto_now_add=True, null=True)),
                ('Updated_On', models.DateField(blank=True, null=True)),
                ('Remarks', models.CharField(blank=True, max_length=100, null=True)),
                ('unique_id', models.CharField(blank=True, max_length=500, null=True, validators=[django.core.validators.MaxLengthValidator(100)])),
                ('uniqueId', models.CharField(blank=True, max_length=500, null=True)),
                ('College_Name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.college')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email_ID', models.CharField(blank=True, max_length=100, null=True)),
                ('First_name', models.CharField(max_length=100, null=True, validators=[django.core.validators.MaxLengthValidator(100)])),
                ('Last_name', models.CharField(max_length=100, null=True, validators=[django.core.validators.MaxLengthValidator(100)])),
                ('Date_Of_Birth', models.DateField(null=True)),
                ('Full_Name', models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.MaxLengthValidator(100)])),
                ('City', models.CharField(max_length=100, null=True)),
                ('Address_Line1', models.CharField(max_length=500, null=True, validators=[django.core.validators.MaxLengthValidator(500)])),
                ('Address_Line2', models.CharField(blank=True, max_length=500, null=True, validators=[django.core.validators.MaxLengthValidator(500)])),
                ('Pincode', models.CharField(blank=True, max_length=100, null=True)),
                ('Name_Of_Department', models.CharField(blank=True, max_length=200, null=True, validators=[django.core.validators.MaxLengthValidator(500)])),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Transgender', 'Transgender')], max_length=100, null=True)),
                ('Nationality', models.CharField(choices=[('Indian', 'Indian')], default='Indian', max_length=100, null=True)),
                ('Designation', models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.MaxLengthValidator(100)])),
                ('Course_Details', models.CharField(blank=True, max_length=200, null=True, validators=[django.core.validators.MaxLengthValidator(200)])),
                ('Date_Of_Joining_Course', models.DateField(blank=True, null=True)),
                ('Course', models.CharField(blank=True, choices=[('BAMS', 'BAMS')], max_length=100, null=True)),
                ('Years', models.CharField(blank=True, choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th'), ('5th', '5th')], max_length=100, null=True)),
                ('Role', models.CharField(blank=True, choices=[('Student', 'Student'), ('Guide', 'Guide')], max_length=100, null=True)),
                ('Correspondence_Sent_To', models.CharField(blank=True, choices=[('Home', 'Home'), ('College', 'College')], max_length=100, null=True)),
                ('Last_Qualifying_Exam_Marksheet', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/')),
                ('Ncism_Teachers_Code', models.CharField(blank=True, max_length=100, null=True)),
                ('is_reviewer', models.BooleanField(default=False)),
                ('Alterner_Email_id', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile', models.CharField(blank=True, max_length=100, null=True)),
                ('Telephone_No', models.CharField(blank=True, max_length=100, null=True)),
                ('OTP_Verified', models.BooleanField(default=False)),
                ('email_confirmed', models.BooleanField(default=False)),
                ('Date_Of_Joining', models.DateField(blank=True, null=True)),
                ('Type_Of_Faculty', models.CharField(blank=True, max_length=100, null=True)),
                ('Updated_On', models.DateField(blank=True, null=True)),
                ('College_Name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collegename', to='account.college')),
                ('District', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.district')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='State_Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject_Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject_Area', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sessions.session')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review_Project_Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Novelity', models.IntegerField(blank=True, null=True)),
                ('Feasibility', models.IntegerField(blank=True, null=True)),
                ('Candidate_Experience', models.IntegerField(blank=True, null=True)),
                ('Relevence_To_Programme', models.IntegerField(blank=True, null=True)),
                ('Guide_Experience', models.IntegerField(blank=True, null=True)),
                ('Total_Marks_review', models.IntegerField(blank=True, null=True)),
                ('Remarks', models.CharField(blank=True, max_length=100, null=True)),
                ('Date_Created', models.DateField(auto_now_add=True, null=True)),
                ('Updated_On', models.DateField(blank=True, null=True)),
                ('Reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Reviewer_ID', to='account.registration')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_ID', to='account.project_info')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='registration',
            name='State',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.state', verbose_name='Student Residence State'),
        ),
        migrations.AddField(
            model_name='registration',
            name='Student_study_state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.state_study'),
        ),
        migrations.AddField(
            model_name='registration',
            name='User_ID',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='register_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project_info',
            name='Guide_ID',
            field=models.OneToOneField(limit_choices_to={'Role': 'Guide'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='GUIDE_ID', to='account.registration'),
        ),
        migrations.AddField(
            model_name='project_info',
            name='Name_Of_Department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.name_of_department'),
        ),
        migrations.AddField(
            model_name='project_info',
            name='Registration_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Registration_ID', to='account.registration'),
        ),
        migrations.AddField(
            model_name='project_info',
            name='Reviewer_ID1',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_reviewer': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Reviewer1_ID', to='account.registration'),
        ),
        migrations.AddField(
            model_name='project_info',
            name='Reviewer_ID2',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_reviewer': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Reviewer2_ID', to='account.registration'),
        ),
        migrations.AddField(
            model_name='project_info',
            name='Reviewer_ID3',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_reviewer': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Reviewer3_ID', to='account.registration'),
        ),
        migrations.AddField(
            model_name='project_info',
            name='Subject_Area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.subject_area'),
        ),
        migrations.AddField(
            model_name='project_info',
            name='User_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Guide_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Designation', models.CharField(blank=True, max_length=100, null=True)),
                ('Name_Of_Department', models.CharField(blank=True, max_length=100, null=True)),
                ('Address_Line1', models.CharField(blank=True, max_length=100, null=True)),
                ('Address_Line2', models.CharField(blank=True, max_length=100, null=True)),
                ('City', models.CharField(blank=True, max_length=100, null=True)),
                ('Pincode', models.CharField(blank=True, max_length=100, null=True)),
                ('Mobile_Number', models.CharField(blank=True, max_length=100, null=True)),
                ('Telephone_No', models.CharField(blank=True, max_length=100, null=True)),
                ('Nationality', models.CharField(blank=True, choices=[('Indian', 'Indian'), ('Foreign', 'Foreign')], max_length=100, null=True)),
                ('Gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Transgender', 'Transgender')], max_length=100, null=True)),
                ('Email_id', models.CharField(blank=True, max_length=100, null=True)),
                ('Updated_On', models.DateField(blank=True, null=True)),
                ('Remarks', models.CharField(blank=True, max_length=100, null=True)),
                ('College_Name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.college')),
                ('District', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.district')),
                ('State', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.state')),
                ('User_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='district',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.state'),
        ),
    ]
